[default]
data_path = "data"
local = "Local.toml" # override configuration
level = "INFO"
address = "0.0.0.0"
port = 8000
limits = { file = 67108864, data-form = 67108864, bytes = 67108864 }
ui_path = "ui"
host = ""

[default.verify]
public_key = ""

[default.switches]
kindle = true
weather = true
bark = true
let_server_run = true
inbox = true
tsdb = true
meme = true
album = true
recipe = true
gate = true
mqtt = true

[default.recipe.s3]
endpoint = ""
region = ""
bucket = ""
access_key = ""
secret_key = ""
enabled = false

[default.kindle]
style = "<0,1,2,3>"
device_name = "kindle"
fonts.main = ""
fonts.weather = ""
fonts.status = ""
dashboard_path = ""

[default.mqtt]
host = ""
port = 1883
username = ""
password = ""
client_id = "secretary"

[default.weather]
cron = "" # second minute hour day month day_of_week year
location = ""
key = ""

[default.bark]
url = ""

[default.let_server_run]
interval = 60
token = ""

[default.let_server_run.executors]
echo = { t = "echo", c = "" }

[default.tsdb]
host = ""
org = ""
token = ""
bucket = ""

[default.meme]
endpoint = ""
region = ""
bucket = ""
access_key = ""
secret_key = ""
jwt_secret_key = ""
jwt_gate = ""
jwt_expire = 3600
hide = []
key_salt = ""
key_file = "meme_key.yaml"
eink_album_width = 800
eink_album_height = 480
s3_concurrency = 16

[default.album]
storage_path = "album"
device_name = "eink_album"
eink_width = 800
eink_height = 480
mqtt_device_ip_topic = "homeassistant/sensor/eink_album/ip/state"
mqtt_device_state_topic = "homeassistant/sensor/eink_album/status/state"
mqtt_button_random_topic = "homeassistant/button/eink_album/random/command"
device_http_endpoint = "http://{ip}/api/upload"
preserve_original = false

[default.gate]
rp_name = ""
rp_id = ""
origin = ""
jwt_secret_key = ""
invite_code_length = 16
invite_ttl = 60

