on:
  push:

jobs:
  autotag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Calver
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          release_branch: autotag
          date_format: "v%Y.%m.%d"
          version_regexp: ^\d+\.\d+\.\d+
          release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.calver.outputs.release }}
          tag_exists_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Deploy
      #   env:
      #     VERSION: ${{ steps.calver.outputs.release }}
      #   run: ./deploy ${VERSION}