on:
  push:

jobs:
  autotag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create git tag
        uses: Digital-Udvikling/actions-calver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
