on:
  push:

jobs:
  main:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools for Rust
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Install dependencies
        run: ./scripts/install.sh
      - name: Build
        run: ./scripts/build.sh ${{matrix.target}}
      - name: Show artifacts
        run: tree ./
        working-directory: ./dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: secretary_${{matrix.target}}
          path: ./dist/*
          if-no-files-found: error
          compression-level: 9
          overwrite: false
